import { useRouter } from "next/router";
import {
  SuccessStyle,
  SuccessStyleInner,
  SuccessHeader,
  SuccessInfos,
  SuccessAdress,
  SuccessProducts,
  KeepShopping,
} from "../styles/SuccessDetails";
import Head from "next/head";
import { FaShoppingCart } from "react-icons/fa";
import Link from "next/link";

const stripe = require("stripe")(
  `${process.env.NEXT_PUBLIC_STRIPE_SECRET_KEY}`
);

export async function getServerSideProps(params) {
  const order = await stripe.checkout.sessions.retrieve(
    params.query.session_id,
    {
      expand: ["line_items"],
    }
  );
  return { props: { order } };
}

export default function Success({ order }) {
  console.log(order);
  const route = useRouter();
  return (
    <>
      <Head>
        <title>LightHouse - Record Shop - Confirmation de commande</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SuccessStyle>
        <SuccessStyleInner
          animate={{ opacity: 1, scale: 1 }}
          initial={{ opacity: 0, scale: 0.75 }}
          transition={{ duration: 0.75 }}
        >
          <SuccessHeader>
            <h3>
              Merci pour votre commande {order.customer_details.name} 😃 !
            </h3>
            <p>
              Un email de confirmation a été envoyé à
              <span>{order.customer_details.email}</span>
            </p>
          </SuccessHeader>
          <SuccessInfos>
            <SuccessAdress>
              <p>
                <b>Adresse : </b>
              </p>
              <p>{order.customer_details.name}</p>
              {Object.entries(order.customer_details.address).map(
                ([key, val]) => (
                  <p key={key}>{val}</p>
                )
              )}
            </SuccessAdress>
            <SuccessProducts>
              <p>
                <b>Commande : </b>
              </p>
              {order.line_items.data.map((item) => (
                <div key={item.id}>
                  <p>
                    {item.description} x {item.quantity}
                  </p>

                  <p>{item.price.unit_amount / 100} €</p>
                </div>
              ))}
            </SuccessProducts>
          </SuccessInfos>
          <Link href={"/"}>
            <KeepShopping
              whileHover={{
                scale: 0.95,
                transition: { duration: 0.3 },
              }}
              whileTap={{ scale: 1.1, transition: { duration: 0.1 } }}
            >
              <span>Continuer vos achats !</span>
              <span>
                <FaShoppingCart />
              </span>
            </KeepShopping>
          </Link>
        </SuccessStyleInner>
      </SuccessStyle>
    </>
  );
}
